default["lampapp"]["database"] = "lampapp"
default["lampapp"]["db_username"] = "lampapp"
default["lampapp"]["path"] = "/var/www/lampapp"
default['lampapp']['server_name'] = "lampapp"
default["lampapp"]["db_user_host"] = "localhost"
